# Generated by Django 4.0.3 on 2022-04-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='User ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Telegram пользователь',
                'verbose_name_plural': 'Telegram пользователи',
                'ordering': ('user_id',),
            },
        ),
    ]
